### CRIAR TABELA COM A DATA DA ÚLTIMA ATUALIZAÇÃO DO ARQUIVO PBI

Linguagem M

let
    Fonte = DateTimeZone.SwitchZone(DateTime.AddZone(DateTime.LocalNow(),3,0),0,0),
    #"Convertido para Tabela" = #table(1, {{Fonte}}),
    #"Tipo Alterado" = Table.TransformColumnTypes(#"Convertido para Tabela",{{"Column1", type date}}),
    #"Colunas Renomeadas" = Table.RenameColumns(#"Tipo Alterado",{{"Column1", "Data_Atualizacao"}})
in
    #"Colunas Renomeadas"

DAX

## Tabela 

Atualização = DateTimeZone.SwitchZone(DateTime.AddZone(DateTime.LocalNow(),3,0),0,0)
Msg Atualizacao = CONCATENATE("Última atualização: ",'Atualização'[Atualização])
